### ISSUE TITLE
Add device count to nodes.json

### ISSUE THREAD

**Issue by colindean** [pittmesh/pittmesh.net#121]
We need to count the number of devices at a site. It's easy to add that count to `nodes.json`. What is hard is changing the code to sum the counts!

**Comment by colindean** [comment]
@Protagonistics Add a `device_count` property to each object in `nodes.json` and I'll write the code to sum it.

Make it like this for each:

```json
{
    "lat": 40.4217654,
    "lon": -79.99593829999998,
    "name": "Sweet Peaches",
    "address": "639 E Warrington Ave, Pittsburgh, PA 15210",
    "hood": "Allentown",
    "status": "live",
    "device_count": 2
  },
```

**Comment by Protagonistics** [comment]
I don't know why it would be hard to sum the counts- you're being done already for number of entries, right?

The device count is a good addition here. I can go through manually and adjust these. Should take 20 minutes.

**Comment by colindean** [comment]
> I don't know why it would be hard to sum the counts- you're being done already for number of entries, right?

It's not hard. It's actually quite easy. The hard part about it is just changing code: I can't do that on Github in a drive-by change!

**Comment by Protagonistics** [comment]
Do or do not. There is no try.

**Comment by Protagonistics** [comment]
So do I just need to go through and add a device_count field?

**Comment by colindean** [comment]
Yep, just like the example.

**Comment by Protagonistics** [comment]
This has been completed.
