### ISSUE TITLE
Move to GeoJSON

### ISSUE THREAD

**Issue by colindean** [pittmesh/pittmesh.net#136]
We should use a standard instead of not using a standard for nodes.json.

https://tools.ietf.org/html/rfc7946

**Comment by colindean** [comment]
I've got https://gist.github.com/colindean/72b8143b2d2caaacc0ba2786f1a9b948 which contains a script that converts `nodes.json` to GeoJSON.

So, the basic data is "there".

Next up is using the new GeoJSON file to generate another GeoJSON FeatureCollection containing the LineStrings describing the point to point links. GeoJSON doesn't let us create LineStrings given a pair of Feature ids.

**Comment by colindean** [comment]
Theoretically, nodes.geojson should be available at http://www.pittmesh.net/node-data/nodes.geojson but there's something going wrong in my deployment process that is causing the generated file not to get deployed with the rest of the files. It was at first a race condition but now there's something else, maybe another race condition.

**Comment by colindean** [comment]
On the generation of LineStrings, `jq` supports merging of [recursive merging of json files](https://stackoverflow.com/questions/19529688/how-to-merge-2-json-file-using-jq#24904276). So, the script that generates the LineStrings based on links.json could just output GeoJSON and `jq` can merge them together into one file.

**Comment by colindean** [comment]
So, I forgot that Heroku doesn't let us really use the filesystem. We have to generate things ahead of time. We'll either have to remember to periodically re-run the script or literally maintain everything in GeoJSON.

Alternative is to have a web service that builds the GeoJSON dynamically. I'm not opposed to that because it's a bit of a stepping stone toward a live data feed (#3).

**Comment by colindean** [comment]
I added the script from the gist above to the `_script` directory in the repo, btw.

**Comment by Protagonistics** [comment]
Are you suggesting that we change nodes.json's format so that it's in GeoJSON format? That shouldn't be hard to edit by hand and add things. I'm ok with that if your'e saying that's what needs doing.

**Comment by colindean** [comment]
Kind of, but geoJson isn't very expressive. That is to say that I think
that I would prefer for you to continue maintaining the format that exists
and me implement a step of the build process that outputs the GeoJson.

I need to think about how this looks in a Heroku world where I am using a
static site generator. I need to see if I can hook into the site generator
to do the conversion work.

**Comment by colindean** [comment]
http://www.pittmesh.net/node-data/nodes.geojson now works 👍

**Comment by colindean** [comment]
Here's an example of how to handle GeoJSON using ModestMaps:

https://github.com/modestmaps/modestmaps-js/blob/master/examples/geojson/index.html

Mapbox might be the better way to go forward. It's [free](https://www.mapbox.com/pricing/) up to a point but I'll bet they've got a non-profit plan. I'm pretty certain that we'd be under their usage limits for a long time, too. Here's their [example of how to load GeoJSON](https://www.mapbox.com/mapbox.js/example/v1.0.0/load-geojson/).

**Comment by colindean** [comment]
Leaflet.js is another option, as it can handle GeoJSON in one function call: http://leafletjs.com/

**Comment by Protagonistics** [comment]
So what exactly do we do to implement this? Do I have to do anything here?

**Comment by colindean** [comment]
There's not presently action for you for this, @Protagonistics. What needs to happen is to rip out the existing ModestMaps implementation and replace it with LeafletJS _after_ I implement something that will pull the links into the GeoJSON file. At present, only the node locations are listed in the GeoJSON available at http://www.pittmesh.net/node-data/nodes.geojson.

**Comment by Protagonistics** [comment]
Ok. I think I understand. I shall ply you with pizza and beer when you return to produce the code.

**Comment by colindean** [comment]
With #165 deploying not to Heroku, the worry about not being able to use the filesystem goes away. 

We'll be able to use the plugin I developed that turns our JSON into GeoJSON. 

However,  I think I'm going to move our JSON to YAML, because that's more user-friendly.

**Comment by colindean** [comment]
Done!
