### ISSUE TITLE
Represent VPN links as differently colored nodes

### ISSUE THREAD

**Issue by colindean** [pittmesh/pittmesh.net#152]
Reticketed from IN-153:

- [x] Change the color of all the pin icons that have a VPN currently to a happy green color 
- [x] Change the color of all the non-VPN pins to "not caution yellow" – using the color of the current VPN links would be fine
- [x] Remove the VPN link lines
- [ ] Change the text in the top paragraph to reflect these changes. Remove the Yellow underline under VPN to remove confusion with that color.

**Comment by colindean** [comment]
I think this will be much easier to do after #136 has the data move to GeoJSON. We'd be better able to represent the type of node and also able to represent links between the nodes in an accepted standard format.

I'll see how much of this I can do before that, though.

**Comment by colindean** [comment]
Presently, there's no relationship between the links and the nodes displayed on the map other than that when the links data loads, the lines are drawn by looking at the lat and lon on the _raw_ nodes data, not the reference to the node after it has been placed on the map. This means that what I _thought_ I could do – change the color of the node at both ends of a VPN line – is not possible.

I _can_ change the color of the nodes on the map to the current color of the VPN line very easily. It's as easy as changing the fill color [here](https://github.com/pittmesh/pittmesh.net/blob/master/node-data/map-pin-live.svg?short_path=d82af23#L55) from `#f41922` to `#FFB90F`, the VPN line color indicated [here](https://github.com/pittmesh/pittmesh.net/blob/master/node-data/map.js#L58). This would make the planned node color pretty close. What color should the planned nodes be?

**Comment by colindean** [comment]
@Protagonistics I might have some time on Sunday to work on this. Let me know what you think about the above.

**Comment by Protagonistics** [comment]
I think we should change regular old pittmesh nodes to a happy green such as #08a400 and the VPN nodes to a blue because they're special like #0080ff .

Iss good? Iss good.

**Comment by colindean** [comment]
That'll quickly address VPN notes, reducing the number of lines to be managed. However, more than 1 line is N lines and still needs to be automated in some way. Thus, it doesn't really reduce the work to be done, just changes it.

**Comment by colindean** [comment]
#08a400 and #0080ff are hard to see on the Terrain tileset we're using.

<img width="275" alt="screen shot 2018-09-02 at 15 54 06" src="https://user-images.githubusercontent.com/197224/44960158-7dad4600-aec8-11e8-9e8c-a12efd966f97.png">

<img width="243" alt="screen shot 2018-09-02 at 15 54 21" src="https://user-images.githubusercontent.com/197224/44960159-8140cd00-aec8-11e8-9a92-8db37eece314.png">

We'll have to find other colors if we want them to stand out better or use another design for the marker in the new Leaftlet.js world.
