### ISSUE TITLE
Deploy to Meta Mesh server

### ISSUE THREAD

**Issue by Justin417** [pittmesh/pittmesh.net#165]
Colin and I spoke and I've offered to move hosting to our server that already hosts our other sites. I will take care of the day to day maintenance and security updates, and Colin will only have to worry about the code (potentially Docker w/ Dokku as a platform). 

Talk to Justin when ready to proceed with this and we'll get setup ASAP.

**Comment by colindean** [comment]
This will most likely involve building the site on Travis and rsync'ing the result to a destination using a [script deployment](https://docs.travis-ci.com/user/deployment/script/).

**Comment by colindean** [comment]
@Justin417, how ready are you for this? I might have the new site done enough to do a test deployment in the next couple of days.

**Comment by Justin417** [comment]
I will have a VM setup for you within the next day up and running at staging.local.pittmesh.net

Login information will be sent to you via a secure medium.

**Comment by colindean** [comment]
👍 I'm very likely to roll with what I've got without using Jekyll. It's a single static page. I've realized that my Jekyll plugin is literally a wrapper around a shell script so I'll just make that shell script a part of the CI build.

**Comment by Protagonistics** [comment]
make it so.

**Comment by Justin417** [comment]
@colindean Login information for the virtual machine has been sent via a Matter Most message.

**Comment by colindean** [comment]
We're doing this now!

**Comment by Justin417** [comment]
Live at https://www.pittmesh.net (and https://pittmesh.net )
