### ISSUE TITLE
Get and re-encrypt new server SSH_PORT, SSH_USER, SSH_HOST

### ISSUE THREAD

**Issue by colindean** [pittmesh/pittmesh.net#183]
@Justin417 will give me these values.

I may need to reconfigure the encrypted SSH private key if he didn't keep the old `authorized_keys` file from the old server.

**Comment by Justin417** [comment]
SSH_PORT = 10196
SSH_USER = sysadmin (I think, it's the same as before)
SSH_HOST = v4deploy.pittmesh.net

Keys should be the same. Thanks!

**Comment by Justin417** [comment]
@colindean I just wanted to follow up with this, is that information sufficient?

**Comment by colindean** [comment]
Oh hey, I never did this!
