### ISSUE TITLE
VPN Links?

### ISSUE THREAD

**Issue by Justin417** [pittmesh/pittmesh.net#42]
Hello,
I was just wondering what you guys would think of showing our VPN links to our remote PittMesh locations on the map? Perhaps instead of a red line they could be a blue line or something of the like. Just to show that those portions are still connected to the larger network. 

Let me know what you guys think.

**Comment by colindean** [comment]
Sure. 

Two ways to do it:

1. Separate links structure, with a separate file and separate (but reused where appropriate) code path.
2. Introduce a “link_type” key in each link in links.json, and map that link type to a color in the links render code.

I think that #2 is probably easier.

**Comment by Protagonistics** [comment]
Yes, let's do 2.

**Comment by colindean** [comment]
OK, go ahead and add that key to each link. I’ll add the color logic sometime this weekend unless Justin gets to it first ;-)

**Comment by Protagonistics** [comment]
make it yellow.

**Comment by Justin417** [comment]
Glad you guys like the idea. 

Colin, if you wouldn’t mind tackling adding the code (I'm no coder, I don't want to break the site)

**Comment by colindean** [comment]
Do something like this:

```json
{
    "from":"Hack Pittsburgh",
    "to":"17th and Jane",
   "type":"wifi"
  },
{
    "from":"Middle of Nowhere",
    "to":"Work Hard PGH",
    "type":"vpn"
  }
```

**Comment by Justin417** [comment]
Sounds good. I'll add the code ASAP.

**Comment by Justin417** [comment]
Alright, I've added the code.
